#!/bin/bash

USERNAME=$(whoami)

cd ~/net.ton.dev/ton/build && crypto/fift -I/home/$USERNAME/net.ton.dev/ton/crypto/fift/lib -s /home/asia/net.ton.dev/ton/crypto/smartcont/new-wallet.fif "${1}" "${2}"
